name: example
description: ShaderFXs example.
publish_to: 'none'

version: 0.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #https://pub.dev/packages/star_menu
  star_menu: ^3.1.4

  #https://pub.dev/packages/hooks_riverpod
  hooks_riverpod: ^2.3.5

  shader_fxs:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/gifs/

  shaders:
    - assets/shaders/radial_blur.frag
    - assets/shaders/zoom_blur.frag
    - assets/shaders/curl_noise.frag
    - assets/shaders/screen_melt.frag
    - assets/shaders/page_curl.frag
    - assets/shaders/noise_fade.frag
    - assets/shaders/ripple.frag
    - assets/shaders/test1.frag
    - assets/shaders/test2.frag
    - assets/shaders/test3.frag
    - assets/shaders/test4.frag
    - assets/shaders/test5.frag